force-app/main/default/objects/Runs__c/Runs__c.object-meta.xml
<CustomObject>
    <description>This shows the runs that have been completed.</description>
    <label>Completed Run</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Runs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Runs__c/fields/Distance_Ran__c.field-meta.xml
<CustomField>
    <fullName>Distance_Ran__c</fullName>
    <description>This shows the distance ran with the word &quot;miles&quot; in front of it.</description>
    <formula>IF(Distance__c &gt; 0,TEXT(Distance__c) &amp;  &quot; Miles&quot;, &quot;N/A&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distance Ran</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Duration_of_Run__c.field-meta.xml
<CustomField>
    <fullName>Duration_of_Run__c</fullName>
    <description>This shows the duration of the run with the word &quot;minutes&quot; in front of it.</description>
    <formula>TEXT(Run_Duration__c) &amp; &quot; minutes&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration of Run</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Run_Date__c</fullName>
    <description>This is the date the run was completed.</description>
    <label>Run Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Run_Duration__c.field-meta.xml
<CustomField>
    <fullName>Run_Duration__c</fullName>
    <description>This is the duration of the run.</description>
    <inlineHelpText>Enter the duration of your run in minutes.</inlineHelpText>
    <label>Run Duration (in minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Run_Type__c.field-meta.xml
<CustomField>
    <fullName>Run_Type__c</fullName>
    <description>This shows the type of run or walk that was completed</description>
    <label>Run Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Treadmill Run</fullName>
            </value>
            <value>
                <fullName>Treadmill Walk</fullName>
            </value>
            <value>
                <fullName>Neighborhood Run</fullName>
            </value>
            <value>
                <fullName>Neighborhood Walk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Runner_Name__c.field-meta.xml
<CustomField>
    <fullName>Runner_Name__c</fullName>
    <description>The name of the runner who completed the run.</description>
    <label>Runner</label>
    <referenceTo>Runner__c</referenceTo>
    <relationshipLabel>Completed Runs</relationshipLabel>
    <relationshipName>Completed_Runs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Runs__c/fields/Type_of_Run_Walk__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Run_Walk__c</fullName>
    <description>This will display an image of the type of run/walk that was completed.</description>
    <formula>IF((TEXT(Run_Type__c) == &quot;Treadmill Run&quot;),IMAGE(&quot;https://akeemadkins-dev-ed--c.documentforce.com/servlet/servlet.FileDownload?file=0153t000003J4eM&quot;, &quot;Treadmill Run&quot;, 100, 150), 
		IF((TEXT(Run_Type__c) == &quot;Treadmill Walk&quot;),IMAGE(&quot;https://akeemadkins-dev-ed--c.documentforce.com/servlet/servlet.FileDownload?file=0153t000003J4eb&quot;, &quot;Treadmill Walk&quot;, 100, 150), 
				IF((TEXT(Run_Type__c) == &quot;Neighborhood Run&quot;),IMAGE(&quot;https://akeemadkins-dev-ed--c.documentforce.com/servlet/servlet.FileDownload?file=0153t000003J4e7&quot;, &quot;Neighborhood Run&quot;, 100, 150), 
						IF((TEXT(Run_Type__c) == &quot;Neighborhood Walk&quot;),IMAGE(&quot;https://akeemadkins-dev-ed--c.documentforce.com/servlet/servlet.FileDownload?file=0153t000003J4eC&quot;, &quot;Treadmill Walk&quot;, 100, 150),&quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type of Run/Walk</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sortRunWalkData.cls
public class sortRunWalkData {

    public String getGetList() {
        return null;
    }
    
   		public String sortPick {get; set;}
    
       private static List <Runs__c> allRuns = new List <Runs__c>();
       public String sortBy = 'Run_Date__c';
       public String ascDesc = 'desc';
    
    public void getSelectOptionValue(){

        
        switch on sortPick {
            when 'Recent'{
                sortBy = 'Run_Date__c';
				ascDesc = 'desc';  
            System.debug('Made it to Recent' + allRuns);

            }
            when 'Name'{
                sortBy = 'Runner_Name__c';
				ascDesc = 'desc';  
           System.debug('Made it to Name' + allRuns);

            }
            when 'Run_Type'{
                sortBy = 'Run_Type__c';
				ascDesc = 'desc';                
            }
            when 'Shortest_Time'{
                sortBy = 'Run_Duration__c';
				ascDesc = 'asc';                
            }
            when 'Longest_Time'{
                sortBy = 'Run_Duration__c';
				ascDesc = 'desc';                
            }
            when 'Shortest_Distance'{
                sortBy = 'Duration_of_Run__c';
				ascDesc = 'asc';                
            }
            when 'Longest_Distance'{
                sortBy = 'Duration_of_Run__c';
				ascDesc = 'desc';                
            }
            when else{
                sortBy = 'Run_Date__c';
				ascDesc = 'desc';                
            }
        }
        runWalkDataQuery();
                
    }
    
    public sortRunWalkData(){
        allRuns = runWalkDataQuery();

        //System.debug('Runs Query: '+allRunsQuery);
        System.debug(allRuns);
    }
    
    public List<Runs__c> runWalkDataQuery(){
        String allRunsQuery = 'SELECT Name, Distance_Ran__c, Duration_of_Run__c, Run_Date__c, Runner_Name__c, Run_Type__c, Type_of_Run_Walk__c FROM Runs__c ';
        allRunsQuery += ' ORDER BY ' + sortBy + ' ' + ascDesc;
        //allRuns = database.query(allRunsQuery);
        return database.query(allRunsQuery);
        
    }
    
    public List<Runs__c> getList(){
        getSelectOptionValue();
        System.debug('called Get List: '+runWalkDataQuery());
        System.debug('SortPick: '+sortBy);
        //runWalkDataQuery();
        return runWalkDataQuery();
    }

}